# Generated by Django 2.1.5 on 2019-03-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='event',
            name='video',
        ),
    ]
