# Generated by Django 2.1.5 on 2019-03-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190325_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='avatar',
            field=models.ImageField(null=True, upload_to='event_pic'),
        ),
    ]
