# Generated by Django 2.1.5 on 2019-03-28 10:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190328_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
